import type { MerchItem } from "./types";

/**
 * Christ Dominion · Youth Week · Keys of the Kingdom merchandise.
 * URLs generated by `npm run upload-merch` (Cloudinary AI background removal
 * is applied asynchronously — first load may still show grey).
 */
export const MERCH_CATALOG: MerchItem[] = [
  {
    id: "jacket-black",
    name: "Christ Dominion Hooded Jacket",
    shortName: "Hooded Jacket",
    type: "clothing",
    price: 65,
    cloudinaryUrl:
      "https://res.cloudinary.com/dpgavffuj/image/upload/q_auto/v1777765632/virtry/merch/jacket-black.png",
  },
  {
    id: "tee-white",
    name: "Keys of the Kingdom Tee",
    shortName: "Kingdom Tee",
    type: "clothing",
    price: 25,
    cloudinaryUrl:
      "https://res.cloudinary.com/dpgavffuj/image/upload/q_auto/v1777765634/virtry/merch/tee-white.png",
  },
  {
    id: "hoodie-navy",
    name: "Keys of the Kingdom Hoodie",
    shortName: "Kingdom Hoodie",
    type: "clothing",
    price: 55,
    cloudinaryUrl:
      "https://res.cloudinary.com/dpgavffuj/image/upload/q_auto/v1777765636/virtry/merch/hoodie-navy.png",
  },
  {
    id: "cap-grey-navy",
    name: "Christ Dominion Snapback",
    shortName: "Snapback Cap",
    type: "headwear",
    price: 20,
    cloudinaryUrl:
      "https://res.cloudinary.com/dpgavffuj/image/upload/q_auto/v1777765638/virtry/merch/cap-grey-navy.png",
  },
  {
    id: "headband-black",
    name: "Keys of the Kingdom Headband",
    shortName: "Headband",
    type: "headwear",
    price: 10,
    cloudinaryUrl:
      "https://res.cloudinary.com/dpgavffuj/image/upload/q_auto/v1777765639/virtry/merch/headband-black.png",
  },
];

export const MERCH_TYPE_LABEL: Record<MerchItem["type"], string> = {
  clothing: "Clothing",
  headwear: "Headwear",
  accessory: "Accessories",
};
